# **SVM Algorithm**

**Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import svm

**Reading the CSV File**

In [ ]:
data = pd.read_csv("glass_identification.csv")
data.head()

ID       RI     Na    Mg    Al     Si     K    Ca   Ba     Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.001     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.000     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.000     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.000     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.000     1

In [ ]:
data.columns

Index(['ID', 'RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

**Modified DataFrame**

In [ ]:
df = data[['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type']]
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba     Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.001     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.000     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.000     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.000     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.000     1

In [ ]:
X = np.asarray(df[['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe']])
Y = np.asarray(df[['Type']])
print(X[:5])
print(Y[:5])

[[1.52101e+00 1.36400e+01 4.49000e+00 1.10000e+00 7.17800e+01 6.00000e-02
  8.75000e+00 0.00000e+00 1.00000e-03]
 [1.51761e+00 1.38900e+01 3.60000e+00 1.36000e+00 7.27300e+01 4.80000e-01
  7.83000e+00 0.00000e+00 0.00000e+00]
 [1.51618e+00 1.35300e+01 3.55000e+00 1.54000e+00 7.29900e+01 3.90000e-01
  7.78000e+00 0.00000e+00 0.00000e+00]
 [1.51766e+00 1.32100e+01 3.69000e+00 1.29000e+00 7.26100e+01 5.70000e-01
  8.22000e+00 0.00000e+00 0.00000e+00]
 [1.51742e+00 1.32700e+01 3.62000e+00 1.24000e+00 7.30800e+01 5.50000e-01
  8.07000e+00 0.00000e+00 0.00000e+00]]
[[1]
 [1]
 [1]
 [1]
 [1]]


**Normalization**

In [ ]:
min_max = MinMaxScaler()
X = min_max.fit(X).transform(X)
X[:5]

array([[0.43283582, 0.43759398, 1.        , 0.25233645, 0.35178571,
        0.00966184, 0.30855019, 0.        , 0.00196078],
       [0.28358209, 0.47518797, 0.80178174, 0.33333333, 0.52142857,
        0.07729469, 0.22304833, 0.        , 0.        ],
       [0.22080773, 0.42105263, 0.79064588, 0.3894081 , 0.56785714,
        0.06280193, 0.21840149, 0.        , 0.        ],
       [0.285777  , 0.37293233, 0.82182628, 0.31152648, 0.5       ,
        0.09178744, 0.25929368, 0.        , 0.        ],
       [0.27524144, 0.38195489, 0.80623608, 0.29595016, 0.58392857,
        0.08856683, 0.24535316, 0.        , 0.        ]])

**Testing & Training Set**

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(171, 9) (171, 1)
(43, 9) (43, 1)


**Gaussian Kernel**

In [ ]:
model = svm.SVC(kernel='rbf')
model.fit(X_train,y_train)
y_hat = model.predict(X_test)
#print(y_hat[:5])
print(confusion_matrix(y_test,y_hat))
print("Accuracy Score :",np.round(accuracy_score(y_test,y_hat)*100,2),"%")

[[ 8  2  0  0  0  0]
 [ 3 12  0  0  0  0]
 [ 1  2  0  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  6  0  0  0  0]
 [ 1  1  0  0  0  6]]
Accuracy Score : 62.79 %


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
model = svm.SVC(kernel='rbf',gamma=0.001,C=0.9)
model.fit(X_train,y_train)
y_hat = model.predict(X_test)
#print(y_hat[:5])
print(confusion_matrix(y_test,y_hat))
print("Accuracy Score :",np.round(accuracy_score(y_test,y_hat)*100,2),"%")

[[ 0 10  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  8  0  0  0  0]]
Accuracy Score : 34.88 %


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Linear Kernel**

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(X_train,y_train)
y_hat = model.predict(X_test)
#print(y_hat[:5])
print(confusion_matrix(y_test,y_hat))
print("Accuracy Score :",np.round(accuracy_score(y_test,y_hat)*100,2),"%")

[[ 6  4  0  0  0  0]
 [ 2 13  0  0  0  0]
 [ 1  2  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  4  0  0  0  2]
 [ 2  1  0  0  0  5]]
Accuracy Score : 55.81 %


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
