In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers.experimental import RandomFourierFeatures
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
data = pd.read_csv("glass_identification.csv")
data.head() 

ID       RI     Na    Mg    Al     Si     K    Ca   Ba     Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.001     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.000     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.000     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.000     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.000     1

In [ ]:
df = data[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','Type']]
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba     Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.001     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.000     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.000     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.000     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.000     1

In [ ]:
X = df[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']].values
Y = df[['Type']].values
print(X[:5],Y[:5])

[[1.52101e+00 1.36400e+01 4.49000e+00 1.10000e+00 7.17800e+01 6.00000e-02
  8.75000e+00 0.00000e+00 1.00000e-03]
 [1.51761e+00 1.38900e+01 3.60000e+00 1.36000e+00 7.27300e+01 4.80000e-01
  7.83000e+00 0.00000e+00 0.00000e+00]
 [1.51618e+00 1.35300e+01 3.55000e+00 1.54000e+00 7.29900e+01 3.90000e-01
  7.78000e+00 0.00000e+00 0.00000e+00]
 [1.51766e+00 1.32100e+01 3.69000e+00 1.29000e+00 7.26100e+01 5.70000e-01
  8.22000e+00 0.00000e+00 0.00000e+00]
 [1.51742e+00 1.32700e+01 3.62000e+00 1.24000e+00 7.30800e+01 5.50000e-01
  8.07000e+00 0.00000e+00 0.00000e+00]] [[1]
 [1]
 [1]
 [1]
 [1]]


In [ ]:
X = MinMaxScaler().fit(X).transform(X.astype(float))
X[:5]

array([[0.43283582, 0.43759398, 1.        , 0.25233645, 0.35178571,
        0.00966184, 0.30855019, 0.        , 0.00196078],
       [0.28358209, 0.47518797, 0.80178174, 0.33333333, 0.52142857,
        0.07729469, 0.22304833, 0.        , 0.        ],
       [0.22080773, 0.42105263, 0.79064588, 0.3894081 , 0.56785714,
        0.06280193, 0.21840149, 0.        , 0.        ],
       [0.285777  , 0.37293233, 0.82182628, 0.31152648, 0.5       ,
        0.09178744, 0.25929368, 0.        , 0.        ],
       [0.27524144, 0.38195489, 0.80623608, 0.29595016, 0.58392857,
        0.08856683, 0.24535316, 0.        , 0.        ]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (171, 9) (171, 1)
Test set: (43, 9) (43, 1)


In [ ]:
model = Sequential()
model.add(Dense(5,activation="relu", input_dim=9))
model.add(Dense(8, activation="sigmoid"))
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
model.fit(X_train,y_train,epochs=1000)

Epoch 1/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.0715
Epoch 2/1000
6/6 [==============================] - 0s 4ms/step - loss: 2.0651
Epoch 3/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0587
Epoch 4/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0524
Epoch 5/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0457
Epoch 6/1000
6/6 [==============================] - 0s 4ms/step - loss: 2.0392
Epoch 7/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0325
Epoch 8/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0257
Epoch 9/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0189
Epoch 10/1000
6/6 [==============================] - 0s 3ms/step - loss: 2.0118
Epoch 11/1000
6/6 [==============================] - 0s 2ms/step - loss: 2.0047
Epoch 12/1000
6/6 [==============================] - 0s 2ms/step - loss: 1.9974
Epoch 13/1000
6/6 [==============================

In [ ]:
y_hat = model.predict(X_test)
y_hat = y_hat.argmax(axis=1)
print("Accuracy Score : ",np.round(metrics.accuracy_score(y_test,y_hat)*100,2),"%")
print(confusion_matrix(y_test,y_hat))
print(classification_report(y_test,y_hat))

Accuracy Score :  58.14 %
[[ 7  3  0  0  0  0]
 [ 3 11  0  0  0  1]
 [ 3  3  0  0  0  0]
 [ 0  0  0  1  0  1]
 [ 0  2  0  0  0  2]
 [ 0  0  0  0  0  6]]
              precision    recall  f1-score   support

           1       0.54      0.70      0.61        10
           2       0.58      0.73      0.65        15
           3       0.00      0.00      0.00         6
           5       1.00      0.50      0.67         2
           6       0.00      0.00      0.00         4
           7       0.60      1.00      0.75         6

    accuracy                           0.58        43
   macro avg       0.45      0.49      0.45        43
weighted avg       0.46      0.58      0.50        43



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
model_1 = Sequential()
model_1.add(Dense(5,activation="relu", input_dim=9))
model_1.add(RandomFourierFeatures(8, kernel_initializer="gaussian"))
model_1.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
model_1.fit(X_train,y_train,epochs=1000)

Epoch 1/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.5810
Epoch 2/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.5091
Epoch 3/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4902
Epoch 4/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4835
Epoch 5/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4764
Epoch 6/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4705
Epoch 7/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4666
Epoch 8/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4624
Epoch 9/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4577
Epoch 10/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.4538
Epoch 11/1000
6/6 [==============================] - 0s 4ms/step - loss: 15.3854
Epoch 12/1000
6/6 [==============================] - 0s 3ms/step - loss: 15.3724
Epoch 13/1000
6/6 [==================

In [ ]:
y_hat = model_1.predict(X_test)
y_hat = y_hat.argmax(axis=1)
print("Accuracy Score : ",np.round(metrics.accuracy_score(y_test,y_hat)*100,2),"%")
print(confusion_matrix(y_test,y_hat))
print(classification_report(y_test,y_hat))

Accuracy Score :  34.88 %
[[ 0  0  0  0  0  0  0]
 [ 5  0  5  0  0  0  0]
 [ 2  0 12  0  1  0  0]
 [ 3  0  3  0  0  0  0]
 [ 0  0  1  0  1  0  0]
 [ 1  0  3  0  0  0  0]
 [ 0  0  1  0  3  0  2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00        10
           2       0.48      0.80      0.60        15
           3       0.00      0.00      0.00         6
           5       0.20      0.50      0.29         2
           6       0.00      0.00      0.00         4
           7       1.00      0.33      0.50         6

    accuracy                           0.35        43
   macro avg       0.24      0.23      0.20        43
weighted avg       0.32      0.35      0.29        43



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

